name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test services
      run: |
        python main.py ergMetersPerDay
        
        python main.py individualContributions
        
        python main.py totalMetersPerSide
        
        python main.py typesOfWorkoutsPerPerson
        
        python main.py workoutsPerPerson
        
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
